name: Danger

on:
  pull_request:
    types: [ opened, synchronize, edited ]
    branches:
      - main
      - 'answer/**'

jobs:
  danger:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # https://github.com/danger/danger/issues/1103#issuecomment-635539947

    - name: Setup Ruby
      uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: '3.0'
        bundler-cache: true

    - name: Setup danger
      run: |
        gem install danger

    - name: Run danger
      run: danger
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}